
services:
  shiny:
    image: rgottberg/dash:latest
    container_name: business_dash_container
    restart: unless-stopped
    ports:
      - "3838:3838"
    volumes:
      - "./app/:/srv/shiny-server"
      - "./log/shiny-server/:/var/log/shiny-server/"
